name: "Henri Palacci's projects in JS and HTML5 for Scientific Presentations "
description: "@henripal's projects in javascript, HTML5, python, thermodynamics, research, science, biology, and grad school things!"

url: "http://henripal.github.io"


markdown: rdiscount
permalink: pretty

gems: 
    - jekyll-sitemap
