name: "@henripal"
description: "Henri Palacci: small interactive scientific projects in JS and HTML5. Molecular dynamics, biological physics, thermodynamics, ..."

url: "http://henripal.github.io"


markdown: rdiscount
permalink: pretty

gems: 
    - jekyll-sitemap
