# Blog settings
permalink: /blog/:title


# My variables
name: Henri Palacci 
description: Physics and Stats 
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", node_modules, gulpfile.js]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
- jekyll-browsersync
