name: "@henripal"
description: "Henri Palacci's projects in JS and HTML5 for more interactive scientific communication,"

url: "http://henripal.github.io"


markdown: rdiscount
permalink: pretty

gems: 
    - jekyll-sitemap
