# Blog settings
permalink: /blog/:title


# My variables
name: Henri Palacci 
description: A Blog About Physics, Machine Learning, and Uncertainty 
google_verification: null
twitter:
  username: henripal
social:
  name: Henri Palacci
  links:
    - https://twitter.com/henripal
    - https://www.linkedin.com/in/henri-palacci-a6974659/


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE", node_modules, gulpfile.js]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

url: "https://henripal.github.io"

plugins:
  - jekyll-browsersync
  - jekyll-seo-tag
  - jekyll-sitemap
